### ISSUE TITLE
middleware use jwt.refresh return "Function () does not exist"

### ISSUE THREAD

**Issue by wind930** [tymondesigns/jwt-auth#171]
Hi @tymondesigns 
I Follow and step by step on the document, but the dingo / api routing when using jwt.refresh, but given "Function () does not exist"

I do not know whether my understanding is biased, I wrote three routes, namely,
1. Log Interface (returning after a successful login generated token)
2. The first step in the return token, http head on request "Authorization Bearer token"

The above two steps are successful. If the token expires, you should request a separate process to get the token refreshed, so I wrote a route below to refresh token

3. $ api-> get ('auth / refresh', ['protected' => false, 'middleware' => 'jwt.refresh'], 'AuthController @ refresh');

Here I have a doubt, if I need AuthController @ refresh 'explicitly call the method and return JWTAuth :: refresh ($ token); or as long as specified in the route' middleware '=>' jwt.refresh 'to

**Comment by wind930** [comment]
###Screen shots

![Route](https://zhaiyonggang.com/software/1.png)

---

![login](https://zhaiyonggang.com/software/2.png)

---

![refresh](https://zhaiyonggang.com/software/3.png)


```php
{
  "message": "Function () does not exist",
  "status_code": 500,
  "debug": {
    "line": 152,
    "file": "\\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Route.php",
    "class": "ReflectionException",
    "trace": [
      "#0 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Route.php(152): ReflectionFunction->__construct('')",
      "#1 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Route.php(130): Illuminate\\\\Routing\\\\Route->runCallable(Object(Dingo\\\\Api\\\\Http\\\\Request))",
      "#2 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Router.php(704): Illuminate\\\\Routing\\\\Route->run(Object(Dingo\\\\Api\\\\Http\\\\Request))",
      "#3 [internal function]: Illuminate\\\\Routing\\\\Router->Illuminate\\\\Routing\\\\{closure}(Object(Dingo\\\\Api\\\\Http\\\\Request))",
      "#4 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Pipeline\\/Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\\\\Api\\\\Http\\\\Request))",
      "#5 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/tymon\\/jwt-auth\\/src\\/Middleware\\/RefreshToken.php(19): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Dingo\\\\Api\\\\Http\\\\Request))",
      "#6 [internal function]: Tymon\\\\JWTAuth\\\\Middleware\\\\RefreshToken->handle(Object(Dingo\\\\Api\\\\Http\\\\Request), Object(Closure))",
      "#7 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Pipeline\\/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#8 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/dingo\\/api\\/src\\/Http\\/Middleware\\/RateLimit.php(65): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Dingo\\\\Api\\\\Http\\\\Request))",
      "#9 [internal function]: Dingo\\\\Api\\\\Http\\\\Middleware\\\\RateLimit->handle(Object(Dingo\\\\Api\\\\Http\\\\Request), Object(Closure))",
      "#10 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Pipeline\\/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#11 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/dingo\\/api\\/src\\/Http\\/Middleware\\/Auth.php(53): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Dingo\\\\Api\\\\Http\\\\Request))",
      "#12 [internal function]: Dingo\\\\Api\\\\Http\\\\Middleware\\\\Auth->handle(Object(Dingo\\\\Api\\\\Http\\\\Request), Object(Closure))",
      "#13 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Pipeline\\/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#14 [internal function]: Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Dingo\\\\Api\\\\Http\\\\Request))",
      "#15 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Pipeline\\/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\\\\Api\\\\Http\\\\Request))",
      "#16 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Router.php(706): Illuminate\\\\Pipeline\\\\Pipeline->then(Object(Closure))",
      "#17 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Router.php(671): Illuminate\\\\Routing\\\\Router->runRouteWithinStack(Object(Illuminate\\\\Routing\\\\Route), Object(Dingo\\\\Api\\\\Http\\\\Request))",
      "#18 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Router.php(631): Illuminate\\\\Routing\\\\Router->dispatchToRoute(Object(Dingo\\\\Api\\\\Http\\\\Request))",
      "#19 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/dingo\\/api\\/src\\/Routing\\/Adapter\\/Laravel.php(65): Illuminate\\\\Routing\\\\Router->dispatch(Object(Dingo\\\\Api\\\\Http\\\\Request))",
      "#20 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/dingo\\/api\\/src\\/Routing\\/Router.php(563): Dingo\\\\Api\\\\Routing\\\\Adapter\\\\Laravel->dispatch(Object(Dingo\\\\Api\\\\Http\\\\Request), 'v1')",
      "#21 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/dingo\\/api\\/src\\/Http\\/Middleware\\/Request.php(91): Dingo\\\\Api\\\\Routing\\\\Router->dispatch(Object(Dingo\\\\Api\\\\Http\\\\Request))",
      "#22 [internal function]: Dingo\\\\Api\\\\Http\\\\Middleware\\\\Request->Dingo\\\\Api\\\\Http\\\\Middleware\\\\{closure}(Object(Dingo\\\\Api\\\\Http\\\\Request))",
      "#23 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Pipeline\\/Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\\\\Api\\\\Http\\\\Request))",
      "#24 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/View\\/Middleware\\/ShareErrorsFromSession.php(54): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Dingo\\\\Api\\\\Http\\\\Request))",
      "#25 [internal function]: Illuminate\\\\View\\\\Middleware\\\\ShareErrorsFromSession->handle(Object(Dingo\\\\Api\\\\Http\\\\Request), Object(Closure))",
      "#26 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Pipeline\\/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#27 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Session\\/Middleware\\/StartSession.php(62): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Dingo\\\\Api\\\\Http\\\\Request))",
      "#28 [internal function]: Illuminate\\\\Session\\\\Middleware\\\\StartSession->handle(Object(Dingo\\\\Api\\\\Http\\\\Request), Object(Closure))",
      "#29 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Pipeline\\/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#30 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Cookie\\/Middleware\\/AddQueuedCookiesToResponse.php(37): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Dingo\\\\Api\\\\Http\\\\Request))",
      "#31 [internal function]: Illuminate\\\\Cookie\\\\Middleware\\\\AddQueuedCookiesToResponse->handle(Object(Dingo\\\\Api\\\\Http\\\\Request), Object(Closure))",
      "#32 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Pipeline\\/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#33 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Cookie\\/Middleware\\/EncryptCookies.php(59): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Dingo\\\\Api\\\\Http\\\\Request))",
      "#34 [internal function]: Illuminate\\\\Cookie\\\\Middleware\\\\EncryptCookies->handle(Object(Dingo\\\\Api\\\\Http\\\\Request), Object(Closure))",
      "#35 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Pipeline\\/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#36 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Foundation\\/Http\\/Middleware\\/CheckForMaintenanceMode.php(42): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Dingo\\\\Api\\\\Http\\\\Request))",
      "#37 [internal function]: Illuminate\\\\Foundation\\\\Http\\\\Middleware\\\\CheckForMaintenanceMode->handle(Object(Dingo\\\\Api\\\\Http\\\\Request), Object(Closure))",
      "#38 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Pipeline\\/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#39 [internal function]: Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Dingo\\\\Api\\\\Http\\\\Request))",
      "#40 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Pipeline\\/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\\\\Api\\\\Http\\\\Request))",
      "#41 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/dingo\\/api\\/src\\/Http\\/Middleware\\/Request.php(92): Illuminate\\\\Pipeline\\\\Pipeline->then(Object(Closure))",
      "#42 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/dingo\\/api\\/src\\/Http\\/Middleware\\/Request.php(73): Dingo\\\\Api\\\\Http\\\\Middleware\\\\Request->sendRequestThroughRouter(Object(Dingo\\\\Api\\\\Http\\\\Request))",
      "#43 [internal function]: Dingo\\\\Api\\\\Http\\\\Middleware\\\\Request->handle(Object(Illuminate\\\\Http\\\\Request), Object(Closure))",
      "#44 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Pipeline\\/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#45 [internal function]: Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))",
      "#46 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Pipeline\\/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\\\\Http\\\\Request))",
      "#47 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Foundation\\/Http\\/Kernel.php(118): Illuminate\\\\Pipeline\\\\Pipeline->then(Object(Closure))",
      "#48 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Foundation\\/Http\\/Kernel.php(86): Illuminate\\\\Foundation\\\\Http\\\\Kernel->sendRequestThroughRouter(Object(Illuminate\\\\Http\\\\Request))",
      "#49 \\/Users\\/apple\\/wind\\/site\\/firecontrol\\/public\\/index.php(54): Illuminate\\\\Foundation\\\\Http\\\\Kernel->handle(Object(Illuminate\\\\Http\\\\Request))",
      "#50 {main}"
    ]
  }
}
```

**Comment by tymondesigns** [comment]
You don't need the `jwt.auth` middleware here. Let dingo handle the authentication
