### ISSUE TITLE
TypeError: Argument 1 passed to Tymon\JWTAuth\Manager::__construct() must be an instance of Tymon\JWTAuth\Contracts\Providers\JWT, null given

### ISSUE THREAD

**Issue by JackDPro** [tymondesigns/jwt-auth#2014]
### Subject of the issue
I installed the jwt-auth library according to the document, and wrote the program according to quick start, which was started with a blank laravel project. But when I visit any api url, an error will be reported ‘TypeError: Argument 1 passed to Tymon\JWTAuth\Manager::__construct() must be an instance of Tymon\JWTAuth\Contracts\Providers\JWT, null given’

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no 
| Framework         | Laravel 
| Framework version | 7.23.1
| Package version   | 1.0.0
| PHP version       |  7.2.5

### logs

```
TypeError: Argument 1 passed to Tymon\JWTAuth\Manager::__construct() must be an instance of Tymon\JWTAuth\Contracts\Providers\JWT, null given, called in /var/www/jwt/vendor/tymon/jwt-auth/src/Providers/AbstractServiceProvider.php on line 216 in file /var/www/jwt/vendor/tymon/jwt-auth/src/Manager.php on line 68

#0 /var/www/jwt/vendor/tymon/jwt-auth/src/Providers/AbstractServiceProvider.php(216): Tymon\JWTAuth\Manager->__construct(NULL, Object(Tymon\JWTAuth\Blacklist), Object(Tymon\JWTAuth\Factory))
#1 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Tymon\JWTAuth\Providers\AbstractServiceProvider->Tymon\JWTAuth\Providers\{closure}(Object(Illuminate\Foundation\Application), Array)
#2 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\Container\Container->build(Object(Closure))
#3 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\Container\Container->resolve('tymon.jwt.manag...', Array, true)
#4 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\Foundation\Application->resolve('tymon.jwt.manag...', Array)
#5 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\Container\Container->make('tymon.jwt.manag...', Array)
#6 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Container/Container.php(1284): Illuminate\Foundation\Application->make('tymon.jwt.manag...')
#7 /var/www/jwt/vendor/tymon/jwt-auth/src/Providers/AbstractServiceProvider.php(258): Illuminate\Container\Container->offsetGet('tymon.jwt.manag...')
#8 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Tymon\JWTAuth\Providers\AbstractServiceProvider->Tymon\JWTAuth\Providers\{closure}(Object(Illuminate\Foundation\Application), Array)
#9 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\Container\Container->build(Object(Closure))
#10 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\Container\Container->resolve('tymon.jwt', Array, true)
#11 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\Foundation\Application->resolve('tymon.jwt', Array)
#12 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\Container\Container->make('tymon.jwt', Array)
#13 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Container/Container.php(1284): Illuminate\Foundation\Application->make('tymon.jwt')
#14 /var/www/jwt/vendor/tymon/jwt-auth/src/Providers/AbstractServiceProvider.php(100): Illuminate\Container\Container->offsetGet('tymon.jwt')
#15 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(111): Tymon\JWTAuth\Providers\AbstractServiceProvider->Tymon\JWTAuth\Providers\{closure}(Object(Illuminate\Foundation\Application), 'api', Array)
#16 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(88): Illuminate\Auth\AuthManager->callCustomCreator('api', Array)
#17 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(68): Illuminate\Auth\AuthManager->resolve('api')
#18 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(54): Illuminate\Auth\AuthManager->guard('api')
#19 [internal function]: Illuminate\Auth\AuthManager->Illuminate\Auth\{closure}(NULL)
#20 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Auth/AuthServiceProvider.php(106): call_user_func(Object(Closure), NULL)
#21 [internal function]: Illuminate\Auth\AuthServiceProvider->Illuminate\Auth\{closure}(NULL)
#22 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Http/Request.php(518): call_user_func(Object(Closure), NULL)
#23 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(97): Illuminate\Http\Request->user()
#24 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(49): Illuminate\Routing\Middleware\ThrottleRequests->resolveRequestSignature(Object(Illuminate\Http\Request))
#25 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\ThrottleRequests->handle(Object(Illuminate\Http\Request), Object(Closure), '60', '1')
#26 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#28 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#29 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#30 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#31 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#32 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#33 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /var/www/jwt/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /var/www/jwt/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#47 /var/www/jwt/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#48 /var/www/jwt/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#49 {main}
```

**Comment by JackDPro** [comment]
I found it was caused by the missing `'jwt' => Tymon\JWTAuth\Providers\JWT\Lcobucci::class,` in jwt.php
