### ISSUE TITLE
Auth driver [jwt] for guard [api] is not defined

### ISSUE THREAD

**Issue by yousefAK** [tymondesigns/jwt-auth#2015]
### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no 
| Framework         | Lumen
| Framework version | 6.3.5
| Package version   | 1.0.0-rc.5
| PHP version       | 7.2

My Application was working without any error, i am using lumen 6.3.5 and jwt 1.0.0-rc5
when i deploy the application again and make composer install, i get this error

```
PHP Fatal error:  Uncaught InvalidArgumentException: Auth driver [jwt] for guard [api] is not defined. in /var/www/html/proj/vendor/illuminate/auth/AuthManager.php:97
Stack trace:
#0 /var/www/html/proj/vendor/illuminate/auth/AuthManager.php(68): Illuminate\Auth\AuthManager->resolve('api')
#1 /var/www/html/proj/vendor/illuminate/auth/AuthManager.php(307): Illuminate\Auth\AuthManager->guard()
#2 /var/www/html/proj/app/Exceptions/Handler.php(44): Illuminate\Auth\AuthManager->__call('user', Array)
#3 /var/www/html/proj/vendor/sentry/sentry/src/State/Hub.php(98): App\Exceptions\Handler->App\Exceptions\{closure}(Object(Sentry\State\Scope))
#4 /var/www/html/proj/vendor/sentry/sentry/src/functions.php(78): Sentry\State\Hub->configureScope(Object(Closure))
#5 /var/www/html/proj/app/Exceptions/Handler.php(48): Sentry\configureScope(Object(Closure))
#6 /var/www/html/proj/vendor/laravel/lumen-framework/src/Concerns/RegistersExceptionHandlers.php(122): App\Exce in /var/www/html/proj/vendor/illuminate/auth/AuthManager.php on line 97
```

now i cannot make any artisan command like (php artisan cache:clear)
every time i try to do anything i get the same error.
by the way the code was working 100% and i was using jwt.

this is my bootstrap/app.php:
```

$app->routeMiddleware([
    'auth' => App\Http\Middleware\Authenticate::class,
    'throttle' => App\Http\Middleware\ThrottleRequests::class,
]);
$app->withFacades(true, [
    Tymon\JWTAuth\Facades\JWTAuth::class => 'JWTAuth',
    Tymon\JWTAuth\Facades\JWTFactory::class => 'JWTFactory',
]);
$app->register(App\Providers\AuthServiceProvider::class);
$app->register(Tymon\JWTAuth\Providers\LumenServiceProvider::class);
```

and this is the auth file:

```
'defaults' => [
        'guard' => env('AUTH_GUARD', 'api'),
        'passwords' => 'users',
    ],
'guards' => [
        'api' => [
            'driver' => 'jwt',
            'provider' => 'users',
        ],
    ],
'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],
    ],
```

**Comment by nicolas-costa** [comment]
Same issue here.

**Comment by dzung1nguyen** [comment]
Laravel 8.0
PHP 7.4
tymon/jwt-auth: ^1.0

In laravel 8.0, same issue if i set default to "api", but if i use Auth::guard('api'), the error will be "Method Illuminate\\Auth\\SessionGuard::factory does not exist."

**Comment by AAmeriyan** [comment]
Same here!!!!!!Any answer???

**Comment by hembachrterran** [comment]
Same problem here while installing Laravel Masterpass plugin.

**Comment by mohamadrezapishdad** [comment]
same here

**Comment by mohamadrezapishdad** [comment]
no solutions yet ?

**Comment by totymedli** [comment]
For me this happened after I upgraded to Laravel 7. According to the upgrade guide `App\Exceptions\Handler` now uses `Throwable` instead of `Exception`. If you have traits used in this handler, update those too.

**Comment by ahad-z** [comment]
1 => This is my config/auth configuration
'api' => [
            'driver' => 'jwt',
            'provider' => 'users',
        ],
2 => This is my authController  
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Tymon\JWTAuth\Facades\JWTAuth;
use App\Models\User;
use Auth;

class LoginController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:api', ['except' => ['login', 'registrtation', 'store','index']]);
    }

    public function index()
    {
    	return view('User.login');

    }

    public function login(Request $request)
    {
        $credentials = $request->only('email', 'password');

        if (! $token = auth('api')->attempt($credentials)) {
            return response()->json(['error' => 'Unauthorized'], 401);
        }


        return $this->respondWithToken($token);

    }

    public function registrtation()
    {
    	return view('User.registration');

    }

    public function store(Request $request)
    {
        

    	$request->validate([
			'name'       => 'required',
			'email'      => 'required|email',
			'password'   => 'required',
			'c_password' => 'same:password',
    	]);

    	try {
    		User::Create(array_merge(
    		$request->except('_token', 'password','c_password'),
    		[
    			'password' => bcrypt($request->password)

    		]
    	));

    	return redirect()->back()->with('success', 'registration success');  
    		
    	} catch (Exception $e) {
    		return response([
    			'message' => $e->getMessage()

    		]);
    	}

    }

    
    public function me()
    {
        $user = User::all();
        return response()->json(['data' => $user]);
    }



    /**
     * Log the user out (Invalidate the token)
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function logout()
    {
       Auth::logout();
        return redirect()->intended('/');
    }

    /**
     * Refresh a token.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function refresh()
    {
        return $this->respondWithToken($this->guard()->refresh());
    }

    /**
     * Get the token array structure.
     *
     * @param  string $token
     *
     * @return \Illuminate\Http\JsonResponse
     */
    protected function respondWithToken($token)
    {
       return response()->json([
            'user' => auth('api')->user(),
            'access_token' => $token,
            'token_type' => 'bearer',
            'expires_in' => 120 * 60
        ]);
    }

    /**
     * Get the guard to be used during authentication.
     *
     * @return \Illuminate\Contracts\Auth\Guard
     */
    public function guard()
    {
        return Auth::guard();
    }
}
3 => This is my api.php configuration 

Route::group(['middleware' => 'auth:api'], function(){
    Route::get('/dashboard',[LoginController::class, 'dashboard'])->name('dashboard');
	Route::get('/logout',[LoginController::class, 'logout'])->name('logout');
	Route::get('/me',[LoginController::class, 'me'])->name('me');
});

And finally please check this composer.json  and my composer.json look like this
 "license": "MIT",
    "require": {
        "php": "^7.3|^8.0",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.12",
        "laravel/tinker": "^2.5",
        "lcobucci/jwt": "3.3.3", // this one for jwt package
        "tymon/jwt-auth": "^1.0" // this one for jwt package
    },
All are problems are done! And work smoothly

**Comment by facueche** [comment]
This worked for me https://github.com/tymondesigns/jwt-auth/issues/1886#issuecomment-538448309 on Laravel 6.0

**Comment by RichieMcMullen** [comment]
Leave the default guard as it is and do this:

```php
'defaults' => [
    'guard' => 'web',
    'passwords' => 'users',
],

'guards' => [
    'web' => [
        'driver' => 'session',
        'provider' => 'users',
    ],

    'api' => [
        'driver' => 'jwt',
        'provider' => 'users',
        'hash' => false,
    ],
],
```

Then just call:

```php 
auth('api')->attempt([....etc
```

**Comment by IDLKZ** [comment]
> 
> 
> Leave the default guard as it is and do this:
> 
> ```
> 'defaults' => [
>     'guard' => 'web',
>     'passwords' => 'users',
> ],
> 
> 'guards' => [
>     'web' => [
>         'driver' => 'session',
>         'provider' => 'users',
>     ],
> 
>     'api' => [
>         'driver' => 'jwt',
>         'provider' => 'users',
>         'hash' => false,
>     ],
> ],
> ```
> 
> Then just call:
> 
> ```
> auth('api')->attempt([....etc
> ```

THANKS FRIEND

**Comment by AbdulrazakZakieh** [comment]
I solved the problem by adding this line to the providers in app.php
`        Tymon\JWTAuth\Providers\LaravelServiceProvider::class,
`
and here is guards I have:
`
'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],
    
	
    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
        'api_customer' => [
             'driver' => 'jwt',
             'provider' => 'api_customer',
        ],`

**Comment by VirtumartOz** [comment]
after following @RichieMcMullen  's solution now my error becomes **Method Illuminate\Auth\SessionGuard::factory does not exist.**

anyone found the solution?

**Comment by dnkmdg** [comment]
> after following @RichieMcMullen 's solution now my error becomes **Method Illuminate\Auth\SessionGuard::factory does not exist.**
> 
> anyone found the solution?

If you follow @RichieMcMullen's solution and then also add the ServiceProvicer as @AbdulrazakZakieh suggestes it will work fine.
