### ISSUE TITLE
Nesbot/Carbon Trailing data error, unexpected data found for login.

### ISSUE THREAD

**Issue by LouisCapelle** [tymondesigns/jwt-auth#2074]
### Carbon\Exceptions\InvalidFormatException: Unexpected data found.
Hello guys, so, i deploy my working project on a VPS to publish my API. So I register a new user in database and its works fine. But when i want to login my user, i got a 500 internal error. It comes from jwt thats calls a package named Nesbot/Carbon. 

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no 
| Framework         | Laravel
| Framework version | 8.18.1 
| Package version   | "tymon/jwt-auth": "^1.0"
| PHP version       | 7.4.3

### Steps to reproduce
You can clone this project :  https://github.com/NemesisOrg/Nemesis-API  on my github. Connect it to a database, create an user with name, email, password, and password_confirmation, on /api/auth/resgiter post route with json body format. And to try to login on route post /api/auth/login with body json format with email and password. 

### Expected behaviour
Actually in dev mode on my computer when y I do my post request i get : {
    "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjE6ODAwMFwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTYwNzUxMDA2OSwiZXhwIjoxNjA3NTEzNjY5LCJuYmYiOjE2MDc1MTAwNjksImp0aSI6Indyd09idWxydG1TbERwTGEiLCJzdWIiOjcsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.JmyOWOC779ZsjOawn85teqkmnMrGGzWX1_czy207CKE",
    "token_type": "bearer",
    "expires_in": 6.0e+32,
    "user": {
        "id": 7,
        "name": "Name ",
        "email": "lEMail",
        "email_verified_at": null,
        "created_at": "2020-12-02T18:58:00.000000Z",
        "updated_at": "2020-12-02T18:58:00.000000Z"
    }
}

### Actual behaviour
And on my VPS I got : 

Carbon\Exceptions\InvalidFormatException: Unexpected data found.
Trailing data in file /usr/share/nginx/html/api/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php on line 643

#0 /usr/share/nginx/html/api/vendor/nesbot/carbon/src/Carbon/Traits/Timestamp.php(49): Carbon\Carbon::rawCreateFromFormat()
#1 /usr/share/nginx/html/api/vendor/tymon/jwt-auth/src/Support/Utils.php(37): Carbon\Carbon::createFromTimestampUTC()
#2 /usr/share/nginx/html/api/vendor/tymon/jwt-auth/src/Support/Utils.php(50): Tymon\JWTAuth\Support\Utils::timestamp()
#3 /usr/share/nginx/html/api/vendor/tymon/jwt-auth/src/Claims/DatetimeTrait.php(83): Tymon\JWTAuth\Support\Utils::isPast()
#4 /usr/share/nginx/html/api/vendor/tymon/jwt-auth/src/Claims/Expiration.php(30): Tymon\JWTAuth\Claims\Expiration->isPast()
#5 [internal function]: Tymon\JWTAuth\Claims\Expiration->validatePayload()
#6 /usr/share/nginx/html/api/vendor/tymon/jwt-auth/src/Claims/Collection.php(61): call_user_func_array()
#7 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(234): Tymon\JWTAuth\Claims\Collection->Tymon\JWTAuth\Claims\{closure}()
#8 /usr/share/nginx/html/api/vendor/tymon/jwt-auth/src/Claims/Collection.php(64): Illuminate\Support\Collection->each()
#9 /usr/share/nginx/html/api/vendor/tymon/jwt-auth/src/Validators/PayloadValidator.php(83): Tymon\JWTAuth\Claims\Collection->validate()
#10 /usr/share/nginx/html/api/vendor/tymon/jwt-auth/src/Validators/PayloadValidator.php(51): Tymon\JWTAuth\Validators\PayloadValidator->validatePayload()
#11 /usr/share/nginx/html/api/vendor/tymon/jwt-auth/src/Payload.php(46): Tymon\JWTAuth\Validators\PayloadValidator->check()
#12 /usr/share/nginx/html/api/vendor/tymon/jwt-auth/src/Factory.php(185): Tymon\JWTAuth\Payload->__construct()
#13 /usr/share/nginx/html/api/vendor/tymon/jwt-auth/src/Factory.php(87): Tymon\JWTAuth\Factory->withClaims()
#14 /usr/share/nginx/html/api/vendor/tymon/jwt-auth/src/JWT.php(234): Tymon\JWTAuth\Factory->make()
#15 /usr/share/nginx/html/api/vendor/tymon/jwt-auth/src/JWT.php(76): Tymon\JWTAuth\JWT->makePayload()
#16 /usr/share/nginx/html/api/vendor/tymon/jwt-auth/src/JWT.php(90): Tymon\JWTAuth\JWT->fromSubject()
#17 /usr/share/nginx/html/api/vendor/tymon/jwt-auth/src/JWTGuard.php(142): Tymon\JWTAuth\JWT->fromUser()
#18 /usr/share/nginx/html/api/vendor/tymon/jwt-auth/src/JWTGuard.php(127): Tymon\JWTAuth\JWTGuard->login()
#19 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(307): Tymon\JWTAuth\JWTGuard->attempt()
#20 /usr/share/nginx/html/api/app/Http/Controllers/AuthController.php(36): Illuminate\Auth\AuthManager->__call()
#21 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\AuthController->login()
#22 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
#23 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\Routing\ControllerDispatcher->dispatch()
#24 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\Routing\Route->runController()
#25 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(692): Illuminate\Routing\Route->run()
#26 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#27 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#28 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#29 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(127): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#30 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(103): Illuminate\Routing\Middleware\ThrottleRequests->handleRequest()
#31 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(55): Illuminate\Routing\Middleware\ThrottleRequests->handleRequestUsingNamedLimiter()
#32 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\ThrottleRequests->handle()
#33 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#34 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(694): Illuminate\Pipeline\Pipeline->then()
#35 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(669): Illuminate\Routing\Router->runRouteWithinStack()
#36 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->runRoute()
#37 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->dispatchToRoute()
#38 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\Routing\Router->dispatch()
#39 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#40 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#41 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#42 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#43 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#44 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#45 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#46 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(87): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#47 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#48 /usr/share/nginx/html/api/vendor/fruitcake/laravel-cors/src/HandleCors.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#49 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors->handle()
#50 /usr/share/nginx/html/api/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#51 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle()
#52 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#53 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\Pipeline\Pipeline->then()
#54 /usr/share/nginx/html/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#55 /usr/share/nginx/html/api/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle()
#56 {main}

**Comment by LouisCapelle** [comment]
I found a fix, if you have this error, check your TTL et check if he is not too high
