### ISSUE TITLE
array_merge(): Expected parameter 2 to be an array, null given

### ISSUE THREAD

**Issue by WangQuanTang** [tymondesigns/jwt-auth#2146]
### Subject of the issue
Hi everybody:
I used jwt to generate token, but it did not take effect, and the following error occurred:

```
{
    "message": "array_merge(): Expected parameter 2 to be an array, null given",
    "status_code": 500,
    "debug": {
        "line": 249,
        "file": "/home/vagrant/code/test/vendor/tymon/jwt-auth/src/JWT.php",
        "class": "ErrorException",
        "trace": [
            "#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()",
            "#1 /home/vagrant/code/test/vendor/tymon/jwt-auth/src/JWT.php(249): array_merge()",
            "#2 /home/vagrant/code/test/vendor/tymon/jwt-auth/src/JWT.php(234): Tymon\\JWTAuth\\JWT->getClaimsArray()",
            "#3 /home/vagrant/code/test/vendor/tymon/jwt-auth/src/JWT.php(76): Tymon\\JWTAuth\\JWT->makePayload()",
            "#4 /home/vagrant/code/test/vendor/tymon/jwt-auth/src/JWT.php(90): Tymon\\JWTAuth\\JWT->fromSubject()",
            "#5 /home/vagrant/code/test/vendor/tymon/jwt-auth/src/JWTGuard.php(142): Tymon\\JWTAuth\\JWT->fromUser()",
            "#6 /home/vagrant/code/test/vendor/tymon/jwt-auth/src/JWTGuard.php(127): Tymon\\JWTAuth\\JWTGuard->login()",
            "#7 /home/vagrant/code/test/app/Http/Controllers/V1/AuthController.php(69): Tymon\\JWTAuth\\JWTGuard->attempt()",
            "#8 /home/vagrant/code/test/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\V1\\AuthController->login()",
            "#9 /home/vagrant/code/test/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()",
            "#10 /home/vagrant/code/test/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch()",
            "#11 /home/vagrant/code/test/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()",
            "#12 /home/vagrant/code/test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()",
            "#13 /home/vagrant/code/test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()",
            "#14 /home/vagrant/code/test/vendor/dingo/api/src/Http/Middleware/PrepareController.php(45): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
            "#15 /home/vagrant/code/test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Dingo\\Api\\Http\\Middleware\\PrepareController->handle()",
            "#16 /home/vagrant/code/test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
            "#17 /home/vagrant/code/test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then()",
            "#18 /home/vagrant/code/test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()",
            "#19 /home/vagrant/code/test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()",
            "#20 /home/vagrant/code/test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()",
            "#21 /home/vagrant/code/test/vendor/dingo/api/src/Routing/Adapter/Laravel.php(88): Illuminate\\Routing\\Router->dispatch()",
            "#22 /home/vagrant/code/test/vendor/dingo/api/src/Routing/Router.php(518): Dingo\\Api\\Routing\\Adapter\\Laravel->dispatch()",
            "#23 /home/vagrant/code/test/vendor/dingo/api/src/Http/Middleware/Request.php(126): Dingo\\Api\\Routing\\Router->dispatch()",
            "#24 /home/vagrant/code/test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}()",
            "#25 /home/vagrant/code/test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
            "#26 /home/vagrant/code/test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()",
            "#27 /home/vagrant/code/test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()",
            "#28 /home/vagrant/code/test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
            "#29 /home/vagrant/code/test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()",
            "#30 /home/vagrant/code/test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()",
            "#31 /home/vagrant/code/test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
            "#32 /home/vagrant/code/test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()",
            "#33 /home/vagrant/code/test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
            "#34 /home/vagrant/code/test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()",
            "#35 /home/vagrant/code/test/vendor/fruitcake/laravel-cors/src/HandleCors.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
            "#36 /home/vagrant/code/test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()",
            "#37 /home/vagrant/code/test/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
            "#38 /home/vagrant/code/test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()",
            "#39 /home/vagrant/code/test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
            "#40 /home/vagrant/code/test/vendor/dingo/api/src/Http/Middleware/Request.php(127): Illuminate\\Pipeline\\Pipeline->then()",
            "#41 /home/vagrant/code/test/vendor/dingo/api/src/Http/Middleware/Request.php(103): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter()",
            "#42 /home/vagrant/code/test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Dingo\\Api\\Http\\Middleware\\Request->handle()",
            "#43 /home/vagrant/code/test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()",
            "#44 /home/vagrant/code/test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()",
            "#45 /home/vagrant/code/test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()",
            "#46 /home/vagrant/code/test/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()",
            "#47 {main}"
        ]
    }
}
```

I located the error position “/home/vagrant/code/test/vendor/tymon/jwt-auth/src/JWT.php” line 249：

![微信截图_20210730155625](https://user-images.githubusercontent.com/52555689/127620814-1567770a-c93c-4902-9c05-2e36d46d822c.png)

And `$this->customClaims` is an array.

![image](https://user-images.githubusercontent.com/52555689/127621078-1c8824fb-a988-4722-aa80-b13c6cc254b9.png)

My  method in controller:

```
public function login(Request $request){
        $credentials = $request->only(['username', 'password']);
        if (!$token = $this->guard()->attempt($credentials)) {
            return response()->json(['error' => 'Unauthorized'], 401);
        }
        return $this->respondWithToken($token);
    }

```

`config/auth.php`:

```
'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'jwt',
            'provider' => 'api',
            'hash' => false,
        ],
    ],

   'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\Models\User::class,
        ],
        'api' => [
            'driver' => 'eloquent',
            'model' => App\Models\User::class,
            'table' => 'user',
        ],
    ],
```
I check previous successful projects, all configurations are the same.And I
I configured the same configuration on the test project, in order to eliminate the interference of the laravel version (v8.1.2. It is the same version as the successful project), the test project also reported the same error.
So, how to solve this problem! Please forgive my  English is poor, all sentences are translated by Google Translate！

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              |  yes
| New Feature?      | no / yes
| Framework         | Laravel
| Framework version | 8.40
| Package version   | 1.0.2
| PHP version       |  7.4.11

**Comment by WangQuanTang** [comment]
This is a very, very low-level mistake, I forgot to write in the model:
![0](https://user-images.githubusercontent.com/52555689/127633903-f59ed6f8-f6f7-4283-a642-5e57fec1ed8e.png)
