### ISSUE TITLE
$app['Tymon\JWTAuth\JWTAuth'] Get into a forever loop

### ISSUE THREAD

**Issue by tienkhoi** [tymondesigns/jwt-auth#220]
Hi All,

Im trying to setup dingo and JWT so I have setup like this
```
 'auth' => [
        'basic' => function ($app) {
            return new Dingo\Api\Auth\Provider\Basic($app['auth'], 'email');
        },
        'jwt' => function ($app) {
            return new Dingo\Api\Auth\Provider\JWT($app['Tymon\JWTAuth\JWTAuth']);

        }
    ],
```
It keep giving me 
```
[2015-08-20 19:49:04] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Maximum function nesting level of '100' reached, aborting!' in /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php:172
Stack trace:
#0 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(133): Symfony\Component\Debug\Exception\FatalErrorException->__construct()
#1 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()
#2 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(256): Illuminate\Container\Container->bind()
#4 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Cache/CacheServiceProvider.php(49): Illuminate\Container\Container->singleton()
#5 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Cache/CacheServiceProvider.php(37): Illuminate\Cache\CacheServiceProvider->registerCommands()
#6 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(531): Illuminate\Cache\CacheServiceProvider->register()
#7 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(648): Illuminate\Foundation\Application->register()
#8 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(628): Illuminate\Foundation\Application->registerDeferredProvider()
#9 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(671): Illuminate\Foundation\Application->loadDeferredProvider()
#10 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(1157): Illuminate\Foundation\Application->make()
#11 /home/vagrant/Projects/calendarP/vendor/tymon/jwt-auth/src/Providers/JWTAuthServiceProvider.php(163): Illuminate\Container\Container->offsetGet()
#12 /home/vagrant/Projects/calendarP/vendor/tymon/jwt-auth/src/Providers/JWTAuthServiceProvider.php(260): Illuminate\Foundation\Bootstrap\LoadConfiguration->{closure:/home/vagrant/Projects/calendarP/config/jwt.php:162-164}()
#13 /home/vagrant/Projects/calendarP/vendor/tymon/jwt-auth/src/Providers/JWTAuthServiceProvider.php(260): call_user_func:{/home/vagrant/Projects/calendarP/vendor/tymon/jwt-auth/src/Providers/JWTAuthServiceProvider.php:260}()
#14 /home/vagrant/Projects/calendarP/vendor/tymon/jwt-auth/src/Providers/JWTAuthServiceProvider.php(149): Tymon\JWTAuth\Providers\JWTAuthServiceProvider->getConfigInstance()
#15 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(274): Tymon\JWTAuth\Providers\JWTAuthServiceProvider->Tymon\JWTAuth\Providers\{closure}()
#16 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(733): Illuminate\Container\Container->Illuminate\Container\{closure}()
#17 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(626): Illuminate\Container\Container->build()
#18 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make()
#19 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(1157): Illuminate\Foundation\Application->make()
#20 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(204): Illuminate\Container\Container->offsetGet()
#21 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(274): Tymon\JWTAuth\Providers\JWTAuthServiceProvider->Tymon\JWTAuth\Providers\{closure}()
#22 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(733): Illuminate\Container\Container->Illuminate\Container\{closure}()
#23 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(626): Illuminate\Container\Container->build()
#24 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make()
#25 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(1157): Illuminate\Foundation\Application->make()
#26 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(172): Illuminate\Container\Container->offsetGet()
#27 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(274): Tymon\JWTAuth\Providers\JWTAuthServiceProvider->Tymon\JWTAuth\Providers\{closure}()
#28 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(733): Illuminate\Container\Container->Illuminate\Container\{closure}()
#29 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(626): Illuminate\Container\Container->build()
#30 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make()
#31 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(1157): Illuminate\Foundation\Application->make()
#32 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(188): Illuminate\Container\Container->offsetGet()
#33 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(274): Tymon\JWTAuth\Providers\JWTAuthServiceProvider->Tymon\JWTAuth\Providers\{closure}()
#34 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(733): Illuminate\Container\Container->Illuminate\Container\{closure}()
#35 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(626): Illuminate\Container\Container->build()
#36 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make()
#37 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(1157): Illuminate\Foundation\Application->make()
#38 /home/vagrant/Projects/calendarP/vendor/laravel/framework/src/Illuminate/Container/Container.php(43): Illuminate\Container\Container->offsetGet()
```

I find out that this line
```
$app['Tymon\JWTAuth\JWTAuth'] 
``` 
leads into an infinity loop.

Any ideas to get around this issue?

Thank you

**Comment by tymondesigns** [comment]
Not sure what could be causing this.. I think it's likely that something else is affecting your issue though, since I haven't seen anyone else with this issue

**Comment by tymondesigns** [comment]
Not sure what could be causing this.. I think it's likely that something else is affecting your issue though, since I haven't seen anyone else with this issue

**Comment by argb** [comment]
I have the same problem too,even I use JWTAuth facade,this issue occour.
