### ISSUE TITLE
Reflection Exception when trying to publish the config

### ISSUE THREAD

**Issue by ayyobro** [tymondesigns/jwt-auth#599]
Here's my setup: 
- Homestead on vagrant
- Laravel 5.2 
- using JWT Auth 0.5.*

Ran composer update, went fine.
Added the service provider and facade items to the app.php config. 

Everything went fine until I tried to run this command:
```
php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\JWTAuthServiceProvider"
```
This is the stack trace that I get back after the error is thrown:
```
PHP Fatal error:  Uncaught ReflectionException: Class log does not exist in /home/vagrant/Sites/topline/vendor/laravel/framework/src/Illuminate/Container/Container.php:738
Stack trace:
#0 /home/vagrant/Sites/topline/vendor/laravel/framework/src/Illuminate/Container/Container.php(738): ReflectionClass->__construct('log')
#1 /home/vagrant/Sites/topline/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build('log', Array)
#2 /home/vagrant/Sites/topline/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(687): Illuminate\Container\Container->make('log', Array)
#3 /home/vagrant/Sites/topline/vendor/laravel/framework/src/Illuminate/Container/Container.php(853): Illuminate\Foundation\Application->make('log')
#4 /home/vagrant/Sites/topline/vendor/laravel/framework/src/Illuminate/Container/Container.php(808): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/vagrant/Sites/topline/vendor/laravel/framework/src/Illuminate/Container/Containe in /home/vagrant/Sites/topline/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 738
```

Any ideas?

**Comment by ayyobro** [comment]
Ignore this one fellas, definitely was a typo in the app.php file. 

I'll just be on my way.
