### ISSUE TITLE
In lumen5.2 create token error

### ISSUE THREAD

**Issue by khlipeng** [tymondesigns/jwt-auth#669]
## Code:

``` php

        // 验证规则
        $rules = array(
            'phone' => array('required', 'numeric', 'regex:/^1[34578][0-9]{9}$/'),
            'password' => array('required', 'alpha_dash'),            
        );
        $payload = app( 'request' )->only( 'phone', 'password' );
        // 验证格式
        $validator = app( 'validator' )->make( $payload, $rules );
        if( $validator->fails() ){
            return response()->json(
                array(
                    'errcode' => -2,
                    'errmsg' => $validator->errors()
                ), 200 );
        }
        $user = Users::where('phone','=',$payload['phone'])->first();
        if(!$user){
            return response()->json(array(
                'errcode' => 400104,
                'errmsg' => '用户不存在'
            ),404);
        }

        if($user->status < 0){
            return response()->json(array(
                'errcode' => 400105,
                'errmsg' => '该账号已被禁止登录'
            ),404);
        }
        try{
            //生成token
            // echo '111';
            if( !$token = JWTAuth::attempt( $payload ) ){
                return response()->json( array(
                    'errcode' => 400103,
                    'errmsg' => '密码错误或账号无效'
                ) );
            }
            echo '111';
            Users::where('id', $user->id)->update(array(
                'last_login' => time()
            ));
        } catch( JWTException $e ){
            return response()->json(
                array(
                    'errcode' => 400102,
                    'errmsg' => '创建Token失败'
                ) );
        }


        return response()->json(
            array(
                'errcode' => 0,
                'errmsg' => '登录成功',
                'data' => array(
                    'token' => $token,
                    'user' => $user
                )
            ) );
```
## Errmsg：

``` javascript
call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\\Auth\\TokenGuard' does not have a method 'once'
```

```
{
        "line": 288,
        "file": "/Users/lipeng/workspres/wanwanhome/sso/vendor/illuminate/auth/AuthManager.php",
        "class": "ErrorException",
        "trace": [
            "#0 [internal function]: Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(2, 'call_user_func_...', '/Users/lipeng/w...', 288, Array)",
            "#1 /Users/lipeng/workspres/wanwanhome/sso/vendor/illuminate/auth/AuthManager.php(288): call_user_func_array(Array, Array)",
            "#2 /Users/lipeng/workspres/wanwanhome/sso/vendor/tymon/jwt-auth/src/Providers/Auth/IlluminateAuthAdapter.php(39): Illuminate\\Auth\\AuthManager->__call('once', Array)",
            "#3 /Users/lipeng/workspres/wanwanhome/sso/vendor/tymon/jwt-auth/src/Providers/Auth/IlluminateAuthAdapter.php(39): Illuminate\\Auth\\AuthManager->once(Array)",
            "#4 /Users/lipeng/workspres/wanwanhome/sso/vendor/tymon/jwt-auth/src/JWTAuth.php(108): Tymon\\JWTAuth\\Providers\\Auth\\IlluminateAuthAdapter->byCredentials(Array)",
            "#5 /Users/lipeng/workspres/wanwanhome/sso/vendor/illuminate/support/Facades/Facade.php(218): Tymon\\JWTAuth\\JWTAuth->attempt(Array)",
            "#6 /Users/lipeng/workspres/wanwanhome/sso/app/Api/Controllers/V1/AuthenticateController.php(48): Illuminate\\Support\\Facades\\Facade::__callStatic('attempt', Array)",
            "#7 /Users/lipeng/workspres/wanwanhome/sso/app/Api/Controllers/V1/AuthenticateController.php(48): Tymon\\JWTAuth\\Facades\\JWTAuth::attempt(Array)",
            "#8 [internal function]: App\\Api\\Controllers\\V1\\AuthenticateController->login()",
            "#9 /Users/lipeng/workspres/wanwanhome/sso/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)",
            "#10 /Users/lipeng/workspres/wanwanhome/sso/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(586): Illuminate\\Container\\Container->call(Array, Array)",
            "#11 /Users/lipeng/workspres/wanwanhome/sso/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(553): Laravel\\Lumen\\Application->callControllerCallable(Array, Array)",
            "#12 /Users/lipeng/workspres/wanwanhome/sso/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(526): Laravel\\Lumen\\Application->callLumenController(Object(App\\Api\\Controllers\\V1\\AuthenticateController), 'login', Array)",
            "#13 /Users/lipeng/workspres/wanwanhome/sso/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(494): Laravel\\Lumen\\Application->callControllerAction(Array)",
            "#14 /Users/lipeng/workspres/wanwanhome/sso/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(474): Laravel\\Lumen\\Application->callActionOnArrayBasedRoute(Array)",
            "#15 [internal function]: Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#16 /Users/lipeng/workspres/wanwanhome/sso/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
            "#17 /Users/lipeng/workspres/wanwanhome/sso/vendor/dingo/api/src/Http/Middleware/PrepareController.php(45): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#18 [internal function]: Dingo\\Api\\Http\\Middleware\\PrepareController->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#19 /Users/lipeng/workspres/wanwanhome/sso/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
            "#20 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#21 /Users/lipeng/workspres/wanwanhome/sso/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
            "#22 [internal function]: Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#23 /Users/lipeng/workspres/wanwanhome/sso/vendor/illuminate/pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
            "#24 /Users/lipeng/workspres/wanwanhome/sso/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(626): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
            "#25 /Users/lipeng/workspres/wanwanhome/sso/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(475): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))",
            "#26 /Users/lipeng/workspres/wanwanhome/sso/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(449): Laravel\\Lumen\\Application->handleFoundRoute(Array)",
            "#27 /Users/lipeng/workspres/wanwanhome/sso/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(381): Laravel\\Lumen\\Application->handleDispatcherResponse(Array)",
            "#28 /Users/lipeng/workspres/wanwanhome/sso/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(629): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}()",
            "#29 /Users/lipeng/workspres/wanwanhome/sso/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(382): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))",
            "#30 /Users/lipeng/workspres/wanwanhome/sso/vendor/dingo/api/src/Routing/Adapter/Lumen.php(103): Laravel\\Lumen\\Application->dispatch(Object(Dingo\\Api\\Http\\Request))",
            "#31 /Users/lipeng/workspres/wanwanhome/sso/vendor/dingo/api/src/Routing/Router.php(574): Dingo\\Api\\Routing\\Adapter\\Lumen->dispatch(Object(Dingo\\Api\\Http\\Request), 'v1')",
            "#32 /Users/lipeng/workspres/wanwanhome/sso/vendor/dingo/api/src/Http/Middleware/Request.php(123): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))",
            "#33 [internal function]: Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#34 /Users/lipeng/workspres/wanwanhome/sso/vendor/illuminate/pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
            "#35 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#36 /Users/lipeng/workspres/wanwanhome/sso/vendor/illuminate/pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
            "#37 /Users/lipeng/workspres/wanwanhome/sso/vendor/dingo/api/src/Http/Middleware/Request.php(124): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
            "#38 /Users/lipeng/workspres/wanwanhome/sso/vendor/dingo/api/src/Http/Middleware/Request.php(100): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))",
            "#39 [internal function]: Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Illuminate\\Http\\Request), Object(Closure))",
            "#40 /Users/lipeng/workspres/wanwanhome/sso/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
            "#41 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
            "#42 /Users/lipeng/workspres/wanwanhome/sso/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))",
            "#43 [internal function]: Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Illuminate\\Http\\Request))",
            "#44 /Users/lipeng/workspres/wanwanhome/sso/vendor/illuminate/pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))",
            "#45 /Users/lipeng/workspres/wanwanhome/sso/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(626): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
            "#46 /Users/lipeng/workspres/wanwanhome/sso/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(382): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))",
            "#47 /Users/lipeng/workspres/wanwanhome/sso/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(327): Laravel\\Lumen\\Application->dispatch(NULL)",
            "#48 /Users/lipeng/workspres/wanwanhome/sso/public/index.php(28): Laravel\\Lumen\\Application->run()",
            "#49 {main}"
        ]
    }
```

**Comment by Fakeronline** [comment]
@khlipeng 5.2版本不支持。所以你还是用5.1吧，表示我也被坑过。

**Comment by khlipeng** [comment]
@Fakeronline 好吧~~，修复了请告知一下~3Q
