### ISSUE TITLE
TokenBlacklistedException Exception not handling in Handler.php in Laravel 5.3

### ISSUE THREAD

**Issue by kushal555** [tymondesigns/jwt-auth#988]
I am trying to handle the ``TokenBlacklistedException``  exception but it never comes in my condition.
it always return the default laravel error log.

 Below i mentioned my App/Exception/Handler.php code.
```php
if ($exception instanceof \Tymon\JWTAuth\Exceptions\TokenInvalidException) {
            $token = \Tymon\JWTAuth\Facades\JWTAuth::getToken();
            $newToken = \Tymon\JWTAuth\Facades\JWTAuth::refresh($token);
            return response(['error' => Lang::get('message.tokeninvalid')], 401)->headers("Authorization", $newToken);
        } else if ($exception instanceof \Tymon\JWTAuth\Exceptions\TokenExpiredException) {
            // Get the New Token

            return response(['error' => Lang::get('message.tokenexpired')], 400);
            #return response(['error' => Lang::get('adminlte_lang::message.tokenexpired')], 401);
        } 
        else if ($exception instanceof \Tymon\JWTAuth\Exceptions\TokenBlacklistedException) {
            
            return response()->json(['error' => Lang::get('message.tokenexpired')], $exception->getStatusCode());
        }
```

What it return 

```
FatalErrorException in JWTManager.php line 84:
Uncaught exception 'Tymon\JWTAuth\Exceptions\TokenBlacklistedException' with message 'The token has been blacklisted' in /opt/lampp/htdocs/Tranzlanta/vendor/tymon/jwt-auth/src/JWTManager.php:84
Stack trace:
#0 /opt/lampp/htdocs/Tranzlanta/vendor/tymon/jwt-auth/src/JWTManager.php(98): Tymon\JWTAuth\JWTManager->decode(Object(Tymon\JWTAuth\Token))
#1 /opt/lampp/htdocs/Tranzlanta/vendor/tymon/jwt-auth/src/JWTAuth.php(144): Tymon\JWTAuth\JWTManager->refresh(Object(Tymon\JWTAuth\Token))
#2 /opt/lampp/htdocs/Tranzlanta/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): Tymon\JWTAuth\JWTAuth->refresh(Object(Tymon\JWTAuth\Token))
#3 /opt/lampp/htdocs/Tranzlanta/app/Exceptions/Handler.php(49): Illuminate\Support\Facades\Facade::__callStatic('refresh', Array)
#4 /opt/lampp/htdocs/Tranzlanta/app/Exceptions/Handler.php(49): Tymon\JWTAuth\Facades\JWTAuth::refresh(Object(Tymon\JWTAuth\Token))
#5 /opt/lampp/htdocs/Tranzlanta/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.p
in JWTManager.php line 84
```

**Comment by wuori** [comment]
I was having this issue too tonight. Doesn't seem like the constructors for the exceptions are setup or are otherwise incomplete. Since I catch most other errors any (on my API) I just put a check on the exception handler (`Handler.php`) for the following:

``` php
        if (strpos($e->getMessage(), 'token')) {
            return response()->json(['token_invalid'], $e->getStatusCode());
        }
```

Not a great solution, but suffices until I get time to make a PR.

**Comment by kushal555** [comment]
@wuori  thanks for your reply, but actually it's not a proper solution. if I integrate it then it will handle all the token related error.
I had another one solution 


```php
      if ($exception instanceof \Symfony\Component\Debug\Exception\FatalErrorException) {
            return response()->json(['token_absent'], 233);
        }
```

the `TokenBlacklistedException` Exception give this exception.
