### ISSUE TITLE
PHP 5.5.9, JWTAuth::invalidate, DateTime::setTimezone() Error

### ISSUE THREAD

**Issue by fahadonline** [tymondesigns/jwt-auth#999]
Hi All,

My server is running PHP 5.5.9.

On logout when I try to JWTAuth::invalidate, I get following error.

"DateTime::setTimezone(): Can only do this for zones with ID for now"

This seems to be PHP bug https://3v4l.org/mlZX7#v527

Any way around other then upgrading PHP ?

```php
{
    "message": "DateTime::setTimezone(): Can only do this for zones with ID for now",
    "status_code": 500,
    "debug": {
        "line": 946,
        "file": "app/vendor/nesbot/carbon/src/Carbon/Carbon.php",
        "class": "ErrorException",
        "trace": [
            "#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'DateTime::setTi...', '/opt/lampp/htdo...', 946, Array)",
            "#1 app/vendor/nesbot/carbon/src/Carbon/Carbon.php(946): DateTime->setTimezone(Object(DateTimeZone))",
            "#2 app/vendor/nesbot/carbon/src/Carbon/Carbon.php(3321): Carbon\\Carbon->setTimezone(Object(DateTimeZone))",
            "#3 app/vendor/nesbot/carbon/src/Carbon/Carbon.php(2462): Carbon\\Carbon->modify('20160 minute')",
            "#4 app/vendor/tymon/jwt-auth/src/Blacklist.php(47): Carbon\\Carbon->addMinutes(20160)",
            "#5 app/vendor/tymon/jwt-auth/src/JWTManager.php(126): Tymon\\JWTAuth\\Blacklist->add(Object(Tymon\\JWTAuth\\Payload))",
            "#6 app/vendor/tymon/jwt-auth/src/JWTAuth.php(158): Tymon\\JWTAuth\\JWTManager->invalidate(Object(Tymon\\JWTAuth\\Token))",
            "#7 app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(217): Tymon\\JWTAuth\\JWTAuth->invalidate('eyJ0eXAiOiJKV1Q...')",
            "#8 app/app/Http/Controllers/Controller.php(103):
```

**Comment by Walk-Code** [comment]
+1

**Comment by Walk-Code** [comment]
You can see this # 1030, hope it can help you.
